### PR TITLE
Added Binding and Web

### PR DESCRIPTION
**Pull request by MohamedEliyas-A**
This project has only binding file and web-related files.

### CODE REVIEW

**Comment by bjornfrantzen** [comment]
A few comments here;

* There is just config for QA here, is that deliberate?
* Are we still doing the AS2->Fileshare and then Fileshare->BTS flow still? Should we not look into having this in one flow and sort out the issues with pipeline-components not working together?
* Does the install-framework (CC + DevOps) support web-receiveports in an application called Bring.Common.AS2? I'm not sure,  but I wonder if there was a requirement earlier that such must be in a 'Web.*' application. Maybe ask Stephen about this?
* Do we really want this to be deployed as both internal and external app? Shouldn't it just be external?
* Will we do any domain-specific processing in this application? Do we really need the reference to Transport.Common here? If not, I think we should remove it.

**Comment by MohamedEliyas-A** [comment]
@bjornfrantzen 
thanks for the review.
My Answers below.
1. Config file updated to all environments.
2. This is a common application for all AS2 partners with no extra processing. The corresponding partner application(in this case Transport2.External.Amazon) has to consume the message in a file share(or whichever feasible) and process the BTS,outbound flow.
3. No, Install framework & DevOps doesn't support this. As this is a one-time installation it is not wise to invest time in automating this. instead, an alternative would be either install it manually(as we did in qa now) or create one dummy BizTalk project with no components so that we can use customdeploy.ps1. 
4. Receiving is an internal project and outbound processing will be external if that is your question. let me know if you have comments.
5. Reference removed.

Refer  [[MB21012601]  Amazon integration](https://kp-confluence.postennorge.no/x/sQWKB) for detailed info on this.

**Comment by bjornfrantzen** [comment]
OK, thanks for good answers.

Will merge as soon as you change the binding a bit, as the code used here won't work when environment is Prod;
You'll end up with two PublicAddress-lines as you will match both the "Prod" and the "Else" one.

image

**Comment by MohamedEliyas-A** [comment]
Well Spotted, I didn't know this. Corrected the error.

**Pull request merged**
